### ISSUE TITLE
NYSIIS should handle number and symbol strings without panic

### ISSUE THREAD

**Issue by jjhendricks** [antzucaro/matchr#6]
If `NYSIIS` function receives a string with only numbers or numbers and symbols it will panic.  The function should probably return an empty string instead ("").  [Line 24](https://github.com/antzucaro/matchr/blob/master/nysiis.go#L24) generates a panic because the input is empty if the string is numbers or symbols only.

I have a fix with tests ready for this in a local branch if you want.  Or you can use this code right about line 24.

```
	// if no characters are left return blank
	if len(input) == 0 {
		return ""
	}
```

Test cases:

```
	{"2002", ""},
	{"1/2", ""},
	{"", ""},
```

**Comment by antzucaro** [comment]
Hey @jjhendricks, thanks so much for reporting this issue! My apologies on that. I created [this pull][pull] to address it. Let me know if that works for you.

[pull]: https://github.com/antzucaro/matchr/pull/7

**Comment by jjhendricks** [comment]
@antzucaro Yep, that works in my tests and in my application.  Thank you for quick resolution and for creating this repository.
